/*global systemDictionary:true */
'use strict';
systemDictionary = {
    'mercury adapter':                                                                {
        'en':    'Adapter settings for mercury',
        'de':    'Adaptereinstellungen für mercury',
        'ru':    'Настройки адаптера mercury',
        'pt':    'Configurações do adaptador para mercury',
        'nl':    'Adapterinstellingen voor mercury',
        'fr':    "Paramètres d'adaptateur pour mercury",
        'it':    "Impostazioni dell'adattatore per mercury",
        'es':    'Ajustes del adaptador para mercury',
        'pl':    'Ustawienia adaptera dla mercury',
        'zh-cn': 'mercury的适配器设置'
    },
    'devices':                                                                        {
        'en':    'Devices',
        'de':    'Geräte',
        'ru':    'Устройства',
        'pt':    'Dispositivos',
        'nl':    'Apparaten',
        'fr':    'Dispositifs',
        'it':    'Dispositivi',
        'es':    'Seadmed',
        'pl':    'Urządzenia',
        'zh-cn': '设备'
    },
    'settings':                                                                       {
        'en':    'Settings',
        'de':    'die Einstellungen',
        'ru':    'Настройки',
        'pt':    'Configurações',
        'nl':    'Instellingen',
        'fr':    'Réglages',
        'it':    'Impostazioni',
        'es':    'Seadistused',
        'pl':    'Ustawienia',
        'zh-cn': '设定值'
    },
    'typeconnect':                                                                    {
        'en':    'Connection type',
        'de':    'Verbindungstyp',
        'ru':    'Тип соединения',
        'pt':    'Tipo de conexão',
        'nl':    'Connectie type',
        'fr':    'Type de connexion',
        'it':    'Tipo di connessione',
        'es':    'ühenduse tüüp',
        'pl':    'Rodzaj połączenia',
        'zh-cn': '连接类型'
    },
    'ip':                                                                             {
        'en':    'IP-address',
        'de':    'IP-adrese',
        'ru':    'IP-адрес',
        'pt':    'IP-endereço ',
        'nl':    'IP-adresse',
        'fr':    'IP-adresse',
        'it':    'IP-indirizzo',
        'es':    'IP-aadress',
        'pl':    'IP-adres',
        'zh-cn': 'IP-地址'
    },
    'tcpport':                                                                        {
        'en':    'Port',
        'de':    'Hafen',
        'ru':    'Порт',
        'pt':    'Porta',
        'nl':    'Port',
        'fr':    'Port',
        'it':    'Porto',
        'es':    'Port',
        'pl':    'Port',
        'zh-cn': '端口'
    },
    'tcp':                                                                            {
        'en':    'TCP/IP',
        'de':    'TCP/IP',
        'ru':    'TCP/IP',
        'pt':    'TCP/IP',
        'nl':    'TCP/IP',
        'fr':    'TCP/IP',
        'it':    'TCP/IP',
        'es':    'TCP/IP',
        'pl':    'TCP/IP',
        'zh-cn': 'TCP/IP'
    },
    'usb':                                                                            {
        'en':    'USB/COM',
        'de':    'USB/COM',
        'ru':    'USB/COM',
        'pt':    'USB/COM',
        'nl':    'USB/COM',
        'fr':    'USB/COM',
        'it':    'USB/COM',
        'es':    'USB/COM',
        'pl':    'USB/COM',
        'zh-cn': 'USB/COM'
    },
    'baud':                                                                           {
        'en':    'Baudrate',
        'de':    'Datenrate',
        'ru':    'Скорость передачи данных',
        'pt':    'Taxa de dados',
        'nl':    'Gegevenssnelheid',
        'fr':    'Débit de données',
        'it':    'Velocità dei dati',
        'es':    'Andmekiirus',
        'pl':    'Szybkość transmisji danych',
        'zh-cn': '资料速率'
    },
    'usbport':                                                                        {
        'en':    'COM-Port',
        'de':    'COM-Hafen',
        'ru':    'COM-Порт',
        'pt':    'COM-Porta',
        'nl':    'COM-Port',
        'fr':    'COM-Port',
        'it':    'COM-Porto',
        'es':    'COM-Port',
        'pl':    'COM-Port',
        'zh-cn': 'COM-端口'
    },
    'parity':                                                                         {
        'en':    'Parity',
        'de':    'Parität',
        'ru':    'Четность',
        'pt':    'Paridade',
        'nl':    'Pariteit',
        'fr':    'La parité',
        'it':    'Parità',
        'es':    'Pariteet',
        'pl':    'Parzystość',
        'zh-cn': '平价'
    },
    'timeoutresponse':                                                                {
        'en':    'Response Timeout (ms)',
        'de':    'Antwortzeitlimit (ms)',
        'ru':    'Время ожидания ответа (мс)',
        'pt':    'Tempo limite de resposta (ms)',
        'nl':    'Time-out van reactie (ms)',
        'fr':    'Délai de réponse (ms)',
        'it':    'Timeout di risposta (ms)',
        'es':    'Vastuse aegumine (ms)',
        'pl':    'Limit czasu odpowiedzi (ms)',
        'zh-cn': '响应超时 (ms)'
    },
    'systemtimeout':                                                                  {
        'en':    'System Timeout (ms)',
        'de':    'System-Timeout (ms)',
        'ru':    'Системный таймаут (мс)',
        'pt':    'Tempo limite de resposta (ms)',
        'nl':    'Systeemtime-out (ms)',
        'fr':    'Délai d\'expiration du système (ms)',
        'it':    'Timeout del sistema (ms)',
        'es':    'Süsteemi aegumine (ms)',
        'pl':    'Limit czasu systemu (ms)',
        'zh-cn': '系统超时 (ms)'
    },
    'factortimeout':                                                                  {
        'en':    'System tmeout multiplier',
        'de':    'System timeout multiplikator',
        'ru':    'Множитель системного таймаута',
        'pt':    'Multiplicador de tempo limite do sistema',
        'nl':    'System timeout multiplier',
        'fr':    'Multiplicateur de délai d\'expiration du système',
        'it':    'Moltiplicatore del timeout di sistema',
        'es':    'Süsteemi ajalõpu kordaja',
        'pl':    'Mnożnik limitu czasu systemu',
        'zh-cn': '系统超时倍增器'
    },
    'model':                                                                          {
        'en':    'Counter model',
        'de':    'Gegenmodell',
        'ru':    'Модель счетчика',
        'pt':    'Modelo de contador',
        'nl':    'Teller model',
        'fr':    'Modèle de compteur',
        'it':    'Contatore modello',
        'es':    'Loendurimudel',
        'pl':    'Model licznika',
        'zh-cn': '柜台型号'
    },
    'address':                                                                        {
        'en':    'Counter network address',
        'de':    'Zählernetzwerkadresse',
        'ru':    'Сетевой адрес счетчика',
        'pt':    'Endereço de rede do contador',
        'nl':    'Teller netwerkadres',
        'fr':    'Adresse réseau du compteur',
        'it':    'Contatore dell\'indirizzo di rete',
        'es':    'Loenduri võrgu aadress',
        'pl':    'Licznik adresu sieciowego',
        'zh-cn': '柜台网络地址'
    },
    'user':                                                                           {
        'en':    'User',
        'de':    'Benutzer',
        'ru':    'Пользователь',
        'pt':    'Usuário',
        'nl':    'Gebruiker',
        'fr':    'Utilisateur',
        'it':    'Utente',
        'es':    'Kasutaja',
        'pl':    'Użytkownik',
        'zh-cn': '用户名'
    },
    'admin':                                                                          {
        'en':    'Administrator',
        'de':    'Admin',
        'ru':    'Администратор',
        'pt':    'Admin',
        'nl':    'Admin',
        'fr':    'Admin',
        'it':    'Amministratore',
        'es':    'Administraator',
        'pl':    'Administrator',
        'zh-cn': '管理员'
    },
    'password':                                                                       {
        'en':    'Password',
        'de':    'Passwort',
        'ru':    'Пароль',
        'pt':    'Senha',
        'nl':    'Wachtwoord',
        'fr':    'Mot de passe',
        'it':    'Password',
        'es':    'Parool',
        'pl':    'Hasło',
        'zh-cn': '密码'
    },
    'name':                                                                           {
        'en':    'Name',
        'de':    'Vorname',
        'ru':    'Имя',
        'pt':    'Primeiro nome',
        'nl':    'Voornaam',
        'fr':    'Prénom',
        'it':    'Nome',
        'es':    'Eesnimi',
        'pl':    'Imię',
        'zh-cn': '名'
    },
    'cancel':                                                                         {
        'en':    'Cancel',
        'de':    'Abbrechen',
        'ru':    'Отмена',
        'pt':    'Cancelar',
        'nl':    'Annuleren',
        'fr':    'Annuler',
        'it':    'cancellazione',
        'es':    'Tühista',
        'pl':    'Anuluj',
        'zh-cn': '取消'
    },
    'agree':                                                                          {
        'en':    'OK',
        'de':    'OK',
        'ru':    'OK',
        'pt':    'OK',
        'nl':    'OK',
        'fr':    'OK',
        'it':    'OK',
        'es':    'OK',
        'pl':    'OK',
        'zh-cn': 'OK'
    },
    'find':                                                                           {
        'en':    'Find',
        'de':    'Zu finden',
        'ru':    'Найти',
        'pt':    'Para encontrar',
        'nl':    'Te vinden',
        'fr':    'Pour trouver',
        'it':    'Da trovare',
        'es':    'Et leida',
        'pl':    'Znaleźć',
        'zh-cn': '寻找'
    },
    'info':                                                                           {
        'en':    'Information',
        'de':    'Informationen',
        'ru':    'Информация',
        'pt':    'Informação',
        'nl':    'Informatie',
        'fr':    'L\'information',
        'it':    'Informazioni',
        'es':    'Teave',
        'pl':    'Informacja',
        'zh-cn': '资讯中心'
    },
    'input addres or sn':                                                             {
        'en':    'Enter counter address or serial number',
        'de':    'Geben Sie die Zähleradresse oder Seriennummer ein',
        'ru':    'Введите адрес или серийный номер счетчика',
        'pt':    'Digite o endereço do contador ou o número de série',
        'nl':    'Voer telleradres of serienummer in',
        'fr':    'Entrez l\'adresse du compteur ou le numéro de série',
        'it':    'Immettere l\'indirizzo del contatore o il numero di serie',
        'es':    'Sisestage loenduri aadress või seerianumber',
        'pl':    'Wpisz adres licznika lub numer seryjny',
        'zh-cn': '输入柜台地址或序列号'
    },
    'add counter':                                                                    {
        'en':    'Add counter',
        'de':    'Zähler hinzufügen',
        'ru':    'Добавить счетчик',
        'pt':    'Adicionar contador',
        'nl':    'Teller toevoegen',
        'fr':    'Ajouter un compteur',
        'it':    'Aggiungi contatore',
        'es':    'Lisage loendur',
        'pl':    'Dodaj licznik',
        'zh-cn': '添加柜台'
    },
    'Error':                                                                          {
        'en':    'Error',
        'de':    'Fehler',
        'ru':    'Ошибка',
        'pt':    'Erro',
        'nl':    'Fout',
        'fr':    'Erreur',
        'it':    'Errore',
        'es':    'Viga',
        'pl':    'Błąd',
        'zh-cn': '失误'
    },
    'extended':                                                                       {
        'en':    'Extended Answer Mode',
        'de':    'Erweiterter Antwortmodus',
        'ru':    'Расширенный режим ответа',
        'pt':    'Modo de resposta estendida',
        'nl':    'Uitgebreide antwoordmodus',
        'fr':    'Mode de réponse étendu',
        'it':    'Modalità di risposta estesa',
        'es':    'Laiendatud vastuse režiim',
        'pl':    'Tryb rozszerzonej odpowiedzi',
        'zh-cn': '扩展应答模式'
    },
    'addres or sn':                                                                   {
        'en':    'Address or Serial Number',
        'de':    'Adresse oder Seriennummer',
        'ru':    'Адрес или серийный номер',
        'pt':    'Endereço ou número de série',
        'nl':    'Adres of serienummer',
        'fr':    'Adresse ou numéro de série',
        'it':    'Indirizzo o numero di serie',
        'es':    'Aadress või seerianumber',
        'pl':    'Adres lub numer seryjny',
        'zh-cn': '地址或序列号'
    },
    'slowPollingTime':                                                                    {
        'en':    'Polling period of non-main parameters (ms)',
        'de':    'Der Zeitraum der Umfrage ist nicht der Hauptparameter (ms)',
        'ru':    'Интервал между опросом не основных параметров (мс)',
        'pt':    'Período de votação de parâmetros não principais (ms)',
        'nl':    'De periode van de enquête is niet de belangrijkste parameter (ms)',
        'fr':    'La période de l\'enquête n\'est pas les principaux paramètres (ms)',
        'it':    'Il periodo del sondaggio non è i parametri principali (ms)',
        'es':    'Uuringu periood ei ole peamised parameetrid (ms)',
        'pl':    'Okres badania nie jest głównymi parametrami (ms)',
        'zh-cn': '调查期不是主要参数 (ms)'
    },
    'fastPollingTime':                                                                    {
        'en':    'Polling period main parameters (ms)',
        'de':    'Der Erhebungszeitraum der Hauptparameter (ms)',
        'ru':    'Интервал между опросом основных параметров (мс)',
        'pt':    'O período da pesquisa dos principais parâmetros (ms)',
        'nl':    'De onderzoeksperiode van de belangrijkste parameters (ms)',
        'fr':    'La période d\'enquête des principaux paramètres (ms)',
        'it':    'Il periodo di rilevamento dei parametri principali (ms)',
        'es':    'Peamiste parameetrite vaatlusperiood (ms)',
        'pl':    'Okres badania głównych parametrów (ms)',
        'zh-cn': '调查期主要参数 (ms)'
    },
    'delete the device':                                                              {
        'en':    'Are you sure you want to delete the device?',
        'de':    'Möchten Sie das Gerät wirklich löschen?',
        'ru':    'Вы действительно хотите удалить устройство?',
        'pt':    'Tem certeza de que deseja excluir o dispositivo?',
        'nl':    'Weet je zeker dat je het apparaat wilt verwijderen?',
        'fr':    'Voulez-vous vraiment supprimer le périphérique?',
        'it':    'Sei sicuro di voler eliminare il dispositivo?',
        'es':    'Kas soovite kindlasti seadme kustutada?',
        'pl':    'Czy na pewno chcesz usunąć urządzenie?',
        'zh-cn': '调查期主要参数'
    },
    'counter card settings':                                                          {
        'en':    'Counter Card Settings',
        'de':    'Zählerkarteneinstellungen',
        'ru':    'Настройки карточки счетчика',
        'pt':    'Configurações do cartão do contador',
        'nl':    'Teller kaartinstellingen',
        'fr':    'Paramètres de la carte de compteur',
        'it':    'Impostazioni della carta contatore',
        'es':    'Loenduri kaardi seaded',
        'pl':    'Ustawienia karty licznika',
        'zh-cn': '柜台卡设置'
    },
    'driver is not running':                                                          {
        'en':    'The driver is not running, first run the driver',
        'de':    'Der Treiber wird nicht ausgeführt. Führen Sie zuerst den Treiber aus',
        'ru':    'Драйвер не запущен, сначала запустите драйвер',
        'pt':    'O driver não está sendo executado, primeiro execute o driver',
        'nl':    'De driver draait niet, voer eerst de driver uit',
        'fr':    'Le pilote ne fonctionne pas, exécutez d\'abord le pilote',
        'it':    'Il driver non è in esecuzione, eseguire prima il driver',
        'es':    'Juht ei tööta, kõigepealt käivitage juht',
        'pl':    'Sterownik nie działa, najpierw uruchom sterownik',
        'zh-cn': '驱动程序未运行，请先运行驱动程序'
    },
    'No response, retry the request':                                                 {
        'en':    'No response, retry the request',
        'de':    'Keine Antwort, wiederholen Sie die Anfrage',
        'ru':    'Нет ответа, повторите запрос',
        'pt':    'Sem resposta, tente novamente a solicitação',
        'nl':    'Geen antwoord, probeer het opnieuw',
        'fr':    'Aucune réponse, réessayez la demande',
        'it':    'Nessuna risposta, ritentare la richiesta',
        'es':    'Vastus puudub, proovige taotlust uuesti',
        'pl':    'Brak odpowiedzi, spróbuj ponownie',
        'zh-cn': '无回应，请重试请求'
    },
    'Error opening communication channel':                                            {
        'en':    'Error opening communication channel',
        'de':    'Fehler beim Öffnen des Kommunikationskanals',
        'ru':    'Ошибка отрытия канала связи',
        'pt':    'Erro ao abrir o canal de comunicação',
        'nl':    'Fout bij openen van communicatiekanaal',
        'fr':    'Erreur lors de l\'ouverture du canal de communication',
        'it':    'Errore durante l\'apertura del canale di comunicazione',
        'es':    'Viga suhtluskanali avamisel',
        'pl':    'Błąd podczas otwierania kanału komunikacji',
        'zh-cn': '打开通讯通道时出错'
    },
    'Invalid data specified':                                                         {
        'en':    'Invalid data specified',
        'de':    'Ungültige Daten angegeben',
        'ru':    'Заданы не корректные данные',
        'pt':    'Dados inválidos especificados',
        'nl':    'Ongeldige gegevens opgegeven',
        'fr':    'Données non valides spécifiées',
        'it':    'Dati specificati non validi',
        'es':    'Täpsustatud on valed andmed',
        'pl':    'Podano nieprawidłowe dane',
        'zh-cn': '指定的数据无效'
    },
    'No response':                                                                    {
        'en':    'No response from the counter',
        'de':    'Keine Antwort vom Zähler',
        'ru':    'Нет ответа от счетчика',
        'pt':    'Nenhuma resposta do contador',
        'nl':    'Geen reactie van de balie',
        'fr':    'Pas de réponse du compteur',
        'it':    'Nessuna risposta dal contatore',
        'es':    'Letilt ei tulnud mingit vastust',
        'pl':    'Brak odpowiedzi z lady',
        'zh-cn': '柜台没有回应'
    },
    'CRC Error':                                                                      {
        'en':    'CRC Error',
        'de':    'Prüfsummenfehler CRC',
        'ru':    'Ошибка котнтрольной суммы CRC',
        'pt':    'Erro de soma de verificação CRC',
        'nl':    'Checksum-fout CRC',
        'fr':    'Erreur de somme de contrôle CRC',
        'it':    'Errore di checksum CRC',
        'es':    'Kontrollsumma viga CRC',
        'pl':    'Błąd sumy kontrolnej CRC',
        'zh-cn': '校验和错误 CRC'
    },
    'Location':                                                                       {
        'en':    'Location',
        'de':    'Lage',
        'ru':    'Местоположение',
        'pt':    'Localização',
        'nl':    'Locatie',
        'fr':    'Emplacement',
        'it':    'Posizione',
        'es':    'Asukoht',
        'pl':    'Lokalizacja',
        'zh-cn': '所在位置'
    },
    'Serial number':                                                                  {
        'en':    'Serial number',
        'de':    'Seriennummer',
        'ru':    'Серийный номер',
        'pt':    'Número de série',
        'nl':    'Serienummer',
        'fr':    'Numéro de série',
        'it':    'Numero di serie',
        'es':    'Seerianumber',
        'pl':    'Numer seryjny',
        'zh-cn': '序列号'
    },
    'Production date':                                                                {
        'en':    'Production date',
        'de':    'Produktionsdatum',
        'ru':    'Дата изготовления',
        'pt':    'Data de produção',
        'nl':    'Productiedatum',
        'fr':    'Date de production',
        'it':    'Data di produzione',
        'es':    'Tootmise kuupäev',
        'pl':    'Data produkcji',
        'zh-cn': '生产日期'
    },
    'Software version':                                                               {
        'en':    'Software version',
        'de':    'Softwareversion',
        'ru':    'Версия ПО',
        'pt':    'Versão do software',
        'nl':    'Softwareversie',
        'fr':    'Version du logiciel',
        'it':    'Versione del software',
        'es':    'Tarkvara versioon',
        'pl':    'Wersja oprogramowania',
        'zh-cn': '软件版本'
    },
    'Everything is fine':                                                             {
        'en':    'Everything is fine',
        'de':    'Alles ist normal',
        'ru':    'Всё в норме',
        'pt':    'Está tudo normal',
        'nl':    'Alles is normaal',
        'fr':    'Tout est normal',
        'it':    'È tutto normale',
        'es':    'Kõik on normaalne',
        'pl':    'Wszystko jest normalne',
        'zh-cn': '一切正常'
    },
    'Invalid command or parameter':                                                   {
        'en':    'Invalid command or parameter',
        'de':    'Ungültiger Befehl oder Parameter',
        'ru':    'Недопустимая команда или параметр',
        'pt':    'Comando ou parâmetro inválido',
        'nl':    'Ongeldige opdracht of parameter',
        'fr':    'Commande ou paramètre non valide',
        'it':    'Comando o parametro non valido',
        'es':    'Kehtetu käsk või parameeter',
        'pl':    'Niepoprawne polecenie lub parametr',
        'zh-cn': '无效的命令或参数'
    },
    'Not enough level to satisfy request':                                            {
        'en':    'Not enough level to satisfy request',
        'de':    'Nicht genug Level, um die Anfrage zu erfüllen',
        'ru':    'Недостаточен уровень для удовлетворения запроса',
        'pt':    'Nível insuficiente para atender à solicitação',
        'nl':    'Onvoldoende niveau om aan verzoek te voldoen',
        'fr':    'Niveau insuffisant pour répondre à la demande',
        'it':    'Livello insufficiente per soddisfare la richiesta',
        'es':    'Taotluse rahuldamiseks pole piisavalt taset',
        'pl':    'Poziom niewystarczający do spełnienia żądania',
        'zh-cn': '等级不足，无法满足要求'
    },
    'The counters internal clock has already been adjusted during the current day.': {
        'en':    'The counter’s internal clock has already been adjusted during the current day',
        'de':    'Die interne Uhr des Zählers wurde bereits am aktuellen Tag eingestellt',
        'ru':    'Внутренние часы счетчика уже корректировались в течение текущих суток',
        'pt':    'O relógio interno do contador já foi ajustado durante o dia atual.',
        'nl':    'De interne klok van de teller is al aangepast tijdens de huidige dag',
        'fr':    'L\'horloge interne du compteur a déjà été ajustée au cours de la journée en cours.',
        'it':    'L\'orologio interno del contatore è già stato regolato durante il giorno corrente.',
        'es':    'Loenduri sisemine kell on praeguse päeva jooksul juba reguleeritud.',
        'pl':    'Wewnętrzny zegar licznika został już wyregulowany w bieżącym dniu.',
        'zh-cn': '该计数器的内部时钟已在当天调整。'
    },
    'Communication channel not open, try again later':                                {
        'en':    'Communication channel not open, try again later',
        'de':    'Kommunikationskanal nicht geöffnet, versuchen Sie es später erneut',
        'ru':    'Не открыт канал связи, повторите попытку позже',
        'pt':    'Canal de comunicação não aberto, tente novamente mais tarde',
        'nl':    'Communicatiekanaal niet geopend, probeer het later opnieuw',
        'fr':    'Le canal de communication n\'est pas ouvert, réessayez plus tard',
        'it':    'Canale di comunicazione non aperto, riprovare più tardi',
        'es':    'Sidekanal pole avatud, proovige hiljem uuesti',
        'pl':    'Kanał komunikacji nie jest otwarty, spróbuj ponownie później',
        'zh-cn': '通讯渠道未打开，请稍后再试'
    },
    'CRC16 software':                                                                 {
        'en':    'CRC16 software',
        'de':    'CRC16 Gerätesoftware',
        'ru':    'CRC16 ПО прибора',
        'pt':    'CRC16 Software do dispositivo',
        'nl':    'CRC16 Apparaatsoftware',
        'fr':    'CRC16 Logiciel de l\'appareil',
        'it':    'CRC16 Software del dispositivo',
        'es':    'CRC16 Seadme tarkvara',
        'pl':    'CRC16 Oprogramowanie urządzenia',
        'zh-cn': 'CRC16 设备软件'
    },
    "Class of energy A+": {
        "en": "Class of energy A+",
        "de": "Energieklasse A+",
        "ru": "Класс энергии А+",
        "pt": "Classe de energia A+",
        "nl": "Energieklasse A+",
        "fr": "Classe d'énergie A+",
        "it": "Classe di energia A+",
        "es": "Clase de energía A+",
        "pl": "Klasa energetyczna A+",
        "zh-cn": "能源等级 A+"
    },
    "Class of energy R+": {
        "en": "Class of energy R+",
        "de": "Energieklasse R+",
        "ru": "Класс энергии R+",
        "pt": "Classe de energia R+",
        "nl": "Energieklasse R+",
        "fr": "Classe d'énergie R+",
        "it": "Classe di energia R+",
        "es": "Clase de energía R+",
        "pl": "Klasa energetyczna R+",
        "zh-cn": "能源等级 R+"
    },
    "Rated voltage": {
        "en": "Rated voltage",
        "de": "Nennspannung",
        "ru": "Номинальное напряжение",
        "pt": "Tensão nominal",
        "nl": "Nominale spanning",
        "fr": "Tension nominale",
        "it": "Tensione nominale",
        "es": "Tensión nominal",
        "pl": "Napięcie znamionowe",
        "zh-cn": "额定电压"
    },
    "Rated current": {
        "en": "Rated current",
        "de": "Nennstrom",
        "ru": "Номинальный ток",
        "pt": "Corrente nominal",
        "nl": "Nominale stroom",
        "fr": "Courant nominal",
        "it": "Corrente nominale",
        "es": "Corriente nominal",
        "pl": "Prąd znamionowy",
        "zh-cn": "额定电流"
    },
    "Number of destinations": {
        "en": "Number of destinations",
        "de": "Anzahl der Ziele",
        "ru": "Количество направлений",
        "pt": "Número de destinos",
        "nl": "Aantal bestemmingen",
        "fr": "Nombre de destinations",
        "it": "Numero di destinazioni",
        "es": "Numero de destinos",
        "pl": "Liczba miejsc docelowych",
        "zh-cn": "目的地数"
    },
    "Temperature Range": {
        "en": "Temperature Range",
        "de": "Temperaturbereich",
        "ru": "Диапазон температур",
        "pt": "Faixa de temperatura",
        "nl": "Temperatuurbereik",
        "fr": "Écart de température",
        "it": "Intervallo di temperatura",
        "es": "Rango de temperatura",
        "pl": "Zakres temperatury",
        "zh-cn": "温度范围"
    },
    "Account of the profile of the average power": {
        "en": "Account of the profile of the average power",
        "de": "Darstellung des Profils der Durchschnittsleistung",
        "ru": "Учет профиля средней мощности",
        "pt": "Conta do perfil da potência média",
        "nl": "Rekening houden met het profiel van het gemiddelde vermogen",
        "fr": "Compte du profil de la puissance moyenne",
        "it": "Conto del profilo della potenza media",
        "es": "Cuenta del perfil de la potencia media.",
        "pl": "Konto profilu średniej mocy",
        "zh-cn": "平均功率曲线图"
    },
    "Number of phases": {
        "en": "Number of phases",
        "de": "Anzahl der Phasen",
        "ru": "Количество фаз",
        "pt": "Número de fases",
        "nl": "Aantal fasen",
        "fr": "Nombre de phases",
        "it": "Numero di fasi",
        "es": "Numero de fases",
        "pl": "Liczba faz",
        "zh-cn": "相数"
    },
    "Constant of counter": {
        "en": "Constant of counter",
        "de": "Konstante des Zählers",
        "ru": "Константа счетчика",
        "pt": "Constante de contador",
        "nl": "Constante van teller",
        "fr": "Constante du compteur",
        "it": "Costante del contatore",
        "es": "Constante de contador",
        "pl": "Stała licznika",
        "zh-cn": "计数器常数"
    },
    "Phases Summation": {
        "en": "Phases Summation",
        "de": "Phasensummierung",
        "ru": "Суммирование фаз",
        "pt": "Soma das fases",
        "nl": "Fase sommatie",
        "fr": "Sommation des phases",
        "it": "Sommatoria delle fasi",
        "es": "Resumen de fases",
        "pl": "Podsumowanie faz",
        "zh-cn": "相加"
    },
    "Tariffication": {
        "en": "Tariffication",
        "de": "Tarifierung",
        "ru": "тарификация",
        "pt": "Tarifação",
        "nl": "Tarifering",
        "fr": "Tarification",
        "it": "tariffazione",
        "es": "Tariffication",
        "pl": "Taryfa",
        "zh-cn": "关税化"
    },
    "Type of counter": {
        "en": "Type of counter",
        "de": "Art des Zählers",
        "ru": "Тип счетчика",
        "pt": "Tipo de contador",
        "nl": "Type teller",
        "fr": "Type de compteur",
        "it": "Tipo di contatore",
        "es": "Tipo de mostrador",
        "pl": "Rodzaj licznika",
        "zh-cn": "柜台类型"
    },
    "Execution option": {
        "en": "Execution option",
        "de": "Ausführungsoption",
        "ru": "Вариант исполнения",
        "pt": "Opção de execução",
        "nl": "Uitvoering optie",
        "fr": "Option d'exécution",
        "it": "Opzione di esecuzione",
        "es": "Opción de ejecución",
        "pl": "Opcja wykonania",
        "zh-cn": "执行选项"
    },
    "Size of menory": {
        "en": "Size of menory",
        "de": "Größe der Menory",
        "ru": "Размер менори",
        "pt": "Tamanho da menory",
        "nl": "Grootte van de menory",
        "fr": "Taille du menory",
        "it": "Dimensione del menory",
        "es": "Tamaño de menory",
        "pl": "Rozmiar menory",
        "zh-cn": "内存大小"
    },
    "Built-in PLM-modem": {
        "en": "Built-in PLM-modem",
        "de": "Eingebautes PLM-Modem",
        "ru": "Встроенный PLM-модем",
        "pt": "Modem PLM incorporado",
        "nl": "Ingebouwde PLM-modem",
        "fr": "Modem PLM intégré",
        "it": "Modem PLM integrato",
        "es": "Módem PLM incorporado",
        "pl": "Wbudowany modem PLM",
        "zh-cn": "内置PLM调制解调器"
    },
    "Built-in GSM-modem": {
        "en": "Built-in GSM-modem",
        "de": "Eingebautes GSM-Modem",
        "ru": "Встроенный GSM-модем",
        "pt": "Modem GSM embutido",
        "nl": "Ingebouwde GSM-modem",
        "fr": "Modem GSM intégré",
        "it": "Modem GSM integrato",
        "es": "Módem GSM incorporado",
        "pl": "Wbudowany modem GSM",
        "zh-cn": "内置GSM调制解调器"
    },
    "Optical port": {
        "en": "Optical port",
        "de": "Optischer Anschluss",
        "ru": "Оптический порт",
        "pt": "Porta óptica",
        "nl": "Optische poort",
        "fr": "Port optique",
        "it": "Porta ottica",
        "es": "Puerto óptico",
        "pl": "Port optyczny",
        "zh-cn": "光口"
    },
    "Type of interface": {
        "en": "Type of interface",
        "de": "Art der Schnittstelle",
        "ru": "Тип интерфейса",
        "pt": "Tipo de interface",
        "nl": "Type interface",
        "fr": "Type d'interface",
        "it": "Tipo di interfaccia",
        "es": "Tipo de interfaz",
        "pl": "Rodzaj interfejsu",
        "zh-cn": "接口类型"
    },
    "External power": {
        "en": "External power",
        "de": "Externe Energie",
        "ru": "Внешняя питание",
        "pt": "Poder externo",
        "nl": "Externe voeding",
        "fr": "Alimentation externe",
        "it": "Potenza esterna",
        "es": "Poder externo",
        "pl": "Zasilanie zewnętrzne",
        "zh-cn": "外接电源"
    },
    "Electronic seal of top cover": {
        "en": "Electronic seal of top cover",
        "de": "Elektronische Dichtung der oberen Abdeckung",
        "ru": "Электронная пломба верхней крышки",
        "pt": "Selo eletrônico da tampa superior",
        "nl": "Elektronisch zegel van bovenklep",
        "fr": "Joint électronique du couvercle supérieur",
        "it": "Sigillo elettronico del coperchio superiore",
        "es": "Sello electrónico de la cubierta superior",
        "pl": "Elektroniczna plomba górnej pokrywy",
        "zh-cn": "顶盖电子封条"
    },
    "Built-in load shedding relay": {
        "en": "Built-in load shedding relay",
        "de": "Eingebautes Lastabwurfrelais",
        "ru": "Встроенное реле отключения нагрузки",
        "pt": "Relé de derramamento de carga integrado",
        "nl": "Ingebouwd afschakelrelais",
        "fr": "Relais de délestage intégré",
        "it": "Relè di distacco del carico incorporato",
        "es": "Relé de descarga de carga incorporado",
        "pl": "Wbudowany przekaźnik zrzutu obciążenia",
        "zh-cn": "内置减载继电器"
    },
    "LCD backlight": {
        "en": "LCD backlight",
        "de": "LCD-Rücklicht",
        "ru": "ЖК подсветка",
        "pt": "Retroiluminação LCD",
        "nl": "LCD-achtergrondverlichting",
        "fr": "LCD rétro-éclairage",
        "it": "Retroilluminazione LCD",
        "es": "LCD luz de fondo",
        "pl": "podświetlenie LCD",
        "zh-cn": "液晶背光"
    },
    "Tariff metering of maximum power": {
        "en": "Tariff metering of maximum power",
        "de": "Tarifmessung der maximalen Leistung",
        "ru": "Тарифный учет максимальной мощности",
        "pt": "Medição tarifária de potência máxima",
        "nl": "Tariefmeting van maximaal vermogen",
        "fr": "Mesure tarifaire de la puissance maximale",
        "it": "Misurazione tariffaria della massima potenza",
        "es": "Medición arancelaria de potencia máxima",
        "pl": "Pomiar taryfowy maksymalnej mocy",
        "zh-cn": "最大功率的电费计量"
    },
    "Electronic seal of protective cover": {
        "en": "Electronic seal of protective cover",
        "de": "Elektronische Versiegelung der Schutzhülle",
        "ru": "Электронная пломба защитного чехла",
        "pt": "Selo eletrônico da capa protetora",
        "nl": "Elektronische afdichting van beschermkap",
        "fr": "Scellé électronique du couvercle de protection",
        "it": "Sigillo elettronico del coperchio protettivo",
        "es": "Sello electrónico de la cubierta protectora",
        "pl": "Elektroniczna plomba osłony ochronnej",
        "zh-cn": "防护罩的电子密封"
    },
    "Interface2": {
        "en": "Interface2",
        "de": "Schnittstelle2",
        "ru": "Interface2",
        "pt": "Interface2",
        "nl": "Interface 2",
        "fr": "Interface2",
        "it": "Interface2",
        "es": "Interfaz2",
        "pl": "Interfejs 2",
        "zh-cn": "接口2"
    },
    "Built-in power of Interface1": {
        "en": "Built-in power of Interface1",
        "de": "Eingebaute Leistung von Interface1",
        "ru": "Встроенная питание интерфейса1",
        "pt": "Potência incorporada da Interface1",
        "nl": "Ingebouwde kracht van Interface 1",
        "fr": "Puissance intégrée d'Interface1",
        "it": "Potenza integrata dell'interfaccia 1",
        "es": "Potencia incorporada de Interface1",
        "pl": "Wbudowana moc interfejsu 1",
        "zh-cn": "Interface1的内置电源"
    },
    "PCE control": {
        "en": "PCE control",
        "de": "PCE-Steuerung",
        "ru": "Контроль ПКЭ",
        "pt": "Controle PCE",
        "nl": "PCE-besturing",
        "fr": "Contrôle PCE",
        "it": "Controllo PCE",
        "es": "Control PCE",
        "pl": "Sterowanie PCE",
        "zh-cn": "PCE控制"
        },
    {
    "Phased energy metering A+": {
        "en": "Phased energy metering A+",
        "de": "Phasenweise Energiemessung A +",
        "ru": "Пофазный учёт энергии А +",
        "pt": "Medição de energia em fases A +",
        "nl": "Gefaseerde energiemeting A +",
        "fr": "Mesure d'énergie par phases A +",
        "it": "Misurazione dell'energia a fasi A +",
        "es": "Medición de energía por fases A +",
        "pl": "Pomiar fazowy energii A +",
        "zh-cn": "分相电能计量A +"
    },
    "Integrated PLC2-modem": {
        "en": "Integrated PLC2-modem",
        "de": "Integriertes PLC2-Modem",
        "ru": "Интегрированный PLC2-модем",
        "pt": "Modem PLC2 integrado",
        "nl": "Geïntegreerd PLC2-modem",
        "fr": "Modem PLC2 intégré",
        "it": "PLC2-modem integrato",
        "es": "Módem PLC2 integrado",
        "pl": "Zintegrowany modem PLC2",
        "zh-cn": "集成式PLC2调制解调器"
    },
    "Profile2": {
        "en": "Profile2",
        "de": "Profil2",
        "ru": "PROFILE2",
        "pt": "Perfil2",
        "nl": "Profiel 2",
        "fr": "Profil2",
        "it": "Profile2",
        "es": "Perfil2",
        "pl": "Profil 2",
        "zh-cn": "Profile2"
    },
    "Electronic seal of modular compartment": {
        "en": "Electronic seal of modular compartment",
        "de": "Elektronische Dichtung des modularen Fachs",
        "ru": "Электронная пломба модульного отсека",
        "pt": "Selo eletrônico do compartimento modular",
        "nl": "Elektronische afdichting van modulair compartiment",
        "fr": "Scellé électronique du compartiment modulaire",
        "it": "Sigillo elettronico del vano modulare",
        "es": "Sello electrónico del compartimento modular.",
        "pl": "Elektroniczne uszczelnienie przedziału modułowego",
        "zh-cn": "模块化隔层的电子密封"
    },
    "Tariff switching by external voltage": {
        "en": "Tariff switching by external voltage",
        "de": "Tarifumschaltung durch externe Spannung",
        "ru": "Переключение тарифов по внешнему напряжению",
        "pt": "Comutação tarifária por tensão externa",
        "nl": "Tariefomschakeling door externe spanning",
        "fr": "Commutation tarifaire par tension externe",
        "it": "Cambio tariffa tramite tensione esterna",
        "es": "Cambio de tarifa por voltaje externo",
        "pl": "Przełączanie taryfy za pomocą napięcia zewnętrznego",
        "zh-cn": "通过外部电压进行电费转换"
    },
    "Voltage transformation ratio": {
        "en": "Voltage transformation ratio",
        "de": "Spannungsumwandlungsverhältnis",
        "ru": "Коэффициент трансформации напряжения",
        "pt": "Relação de transformação de tensão",
        "nl": "Spanningstransformatieverhouding",
        "fr": "Rapport de transformation de tension",
        "it": "Rapporto di trasformazione della tensione",
        "es": "Relación de transformación de voltaje",
        "pl": "Współczynnik transformacji napięcia",
        "zh-cn": "电压变比"
    },
    "Current transformer ratio": {
        "en": "Current transformer ratio",
        "de": "Stromwandlerverhältnis",
        "ru": "Коэффициент трансформатора тока",
        "pt": "Relação do transformador de corrente",
        "nl": "Huidige transformatorverhouding",
        "fr": "Rapport de transformateur de courant",
        "it": "Rapporto del trasformatore di corrente",
        "es": "Relación transformador de corriente",
        "pl": "Współczynnik przekładnika prądowego",
        "zh-cn": "电流互感器比例"
    },
    "cosfTotal": {
        "en": "Power factor average",
        "de": "Leistungsfaktor Durchschnitt",
        "ru": "Коэффициент мощности средний",
        "pt": "Fator de potência médio",
        "nl": "Power factor gemiddeld",
        "fr": "Facteur de puissance moyen",
        "it": "Fattore di potenza medio",
        "es": "Factor de potencia promedio",
        "pl": "Średni współczynnik mocy",
        "zh-cn": "功率因数平均值"
        }
};

/*          totalEnergyActivePlus:          {val: null, desc: 'Общая энергия от сброса A+'},
            totalEnergyActiveMinus:         {val: null, desc: 'Общая энергия от сброса A-'},
            totalEnergyReactivePlus:        {val: null, desc: 'Общая энергия от сброса R+'},
            totalEnergyReactiveMinus:       {val: null, desc: 'Общая энергия от сброса R-'},
            totalEnergy:                    {val: null, desc: 'Общая энергия'},
            currentYearEnergyActivePlus:    {val: null, desc: 'Энергия за текущий год A+'},
            currentYearEnergyActiveMinus:   {val: null, desc: 'Энергия за текущий год A-'},
            currentYearEnergyReactivePlus:  {val: null, desc: 'Энергия за текущий год R+'},
            currentYearEnergyReactiveMinus: {val: null, desc: 'Энергия за текущий год R-'},
            currentYearEnergyTotal:         {val: null, desc: 'Энергия за текущий'},
            currentDayEnergyActivePlus:     {val: null, desc: 'Энергия за текущий день A+'},
            currentDayEnergyActiveMinus:    {val: null, desc: 'Энергия за текущий день A-'},
            currentDayEnergyReactivePlus:   {val: null, desc: 'Энергия за текущий день R+'},
            currentDayEnergyReactiveMinus:  {val: null, desc: 'Энергия за текущий день R-'},
            currentDayEnergyTotal:          {val: null, desc: 'Энергия за текущий'},
            oneTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 1 тарифу активная прямая'},
            oneTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 1 тарифу активная обратная'},
            oneTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 1 тарифу реактивная прямая'},
            oneTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 1 тарифу реактивная обратная'},
            oneTarrifEnergyTotal:           {val: null, desc: 'Энергия по 1 тарифу'},
            twoTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 2 тарифу активная прямая'},
            twoTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 2 тарифу активная обратная'},
            twoTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 2 тарифу реактивная прямая'},
            twoTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 2 тарифу реактивная обратная'},
            twoTarrifEnergyTotal:           {val: null, desc: 'Энергия по 2 тарифу'},
            threeTarrifEnergyActivePlus:    {val: null, desc: 'Энергия по 3 тарифу активная прямая'},
            threeTarrifEnergyActiveMinus:   {val: null, desc: 'Энергия по 3 тарифу активная обратная'},
            threeTarrifEnergyReactivePlus:  {val: null, desc: 'Энергия по 3 тарифу реактивная прямая'},
            threeTarrifEnergyReactiveMinus: {val: null, desc: 'Энергия по 3 тарифу реактивная обратная'},
            threeTarrifEnergyTotal:         {val: null, desc: 'Энергия по 3 тарифу'},
            fourTarrifEnergyActivePlus:     {val: null, desc: 'Энергия по 4 тарифу активная прямая'},
            fourTarrifEnergyActiveMinus:    {val: null, desc: 'Энергия по 4 тарифу активная обратная'},
            fourTarrifEnergyReactivePlus:   {val: null, desc: 'Энергия по 4 тарифу реактивная прямая'},
            fourTarrifEnergyReactiveMinus:  {val: null, desc: 'Энергия по 4 тарифу реактивная обратная'},
            fourTarrifEnergyTotal:          {val: null, desc: 'Энергия по 4 тарифу'},
            powerTotal:                     {val: null, desc: 'Мощность общая'},
            powerPhase1:                    {val: null, desc: 'Мощность на 1 фазе'},
            powerPhase2:                    {val: null, desc: 'Мощность на 2 фазе'},
            powerPhase3:                    {val: null, desc: 'Мощность на 3 фазе'},
            voltagePhase1:                  {val: null, desc: 'Напряжение 1 фазы'},
            voltagePhase2:                  {val: null, desc: 'Напряжение 2 фазы'},
            voltagePhase3:                  {val: null, desc: 'Напряжение 3 фазы'},
            currentPhase1:                  {val: null, desc: 'Ток 1 фазы'},
            currentPhase2:                  {val: null, desc: 'Ток 2 фазы'},
            currentPhase3:                  {val: null, desc: 'Ток 3 фазы'},
            //cosfTotal:                      {val: null, desc: 'Коэффициент мощности средний'},
            cosfPhase1:                     {val: null, desc: 'Коэффициент мощности по 1 фазе'},
            cosfPhase2:                     {val: null, desc: 'Коэффициент мощности по 2 фазе'},
            cosfPhase3:                     {val: null, desc: 'Коэффициент мощности по 3 фазе'},*/
